[package]
name = "zksync"
version = "0.1.0"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
edition = "2018"

[dependencies]
zksync_types = { path = "../../core/lib/types", version = "1.0" }
zksync_eth_client = { path = "../../core/lib/eth_client", version = "1.0" }
zksync_eth_signer = { path = "../../core/lib/eth_signer", version = "1.0" }
zksync_crypto = { path = "../../core/lib/crypto", version = "1.0" }
zksync_utils = { path = "../../core/lib/utils", version = "1.0" }
zksync_contracts = { path = "../../core/lib/contracts", version = "1.0" }

bellman = { package = "bellman_ce", git = "https://github.com/matter-labs/bellman", branch = "plonk_release" }
sha2 = "0.8"
web3 = "0.13.0"
ethabi = "12.0.0"
tokio = { version = "0.2", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }

serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.0"

reqwest = { version = "0.10", features = ["json", "blocking"] }
thiserror = "1.0"

jsonrpc-core = "14.0.3"

num = { version = "0.2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"

[features]
integration-tests = []
