/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ZkSync */

#ifndef _Included_ZkSync
#define _Included_ZkSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ZkSync
 * Method:    privateKeyToPublicKeyHash
 * Signature: (LZkSync;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ZkSync_privateKeyToPublicKeyHash
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
